name: 'Checkout'
description: 'Checkout a Git repository at a particular version'

inputs:
  repository:
    description: 'Repository name with owner (e.g., actions/checkout)'
    default: ${{ github.repository }}

  ref:
    description: >
      The branch, tag, or SHA to checkout. Defaults to the reference or SHA for the triggering event.
      Uses the default branch if triggered manually.
    default: ${{ github.event.ref || github.event.after }}

  token:
    description: >
      Personal access token (PAT) used to fetch the repository.
      Configured with the local git config for authenticated git commands.
      Remove the PAT in the post-job step.
    default: ${{ github.token }}

  ssh-key:
    description: >
      SSH key used to fetch the repository.
      Configured with the local git config for authenticated git commands.
      Remove the SSH key in the post-job step.
    default: ${{ secrets.SSH_KEY }}

  ssh-known-hosts:
    description: >
      Additional known hosts for SSH key authentication.
      Use `ssh-keyscan` utility to obtain public keys.
    default: null

  ssh-strict:
    description: >
      Perform strict host key checking.
      Adds `StrictHostKeyChecking=yes` and `CheckHostIP=no` when true.
      Use `ssh-known-hosts` to configure additional hosts.
    default: true

  persist-credentials:
    description: 'Configure token or SSH key with local git config'
    default: true

  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ${{ github.workspace }}

  clean:
    description: 'Execute `git clean -ffdx && git reset --hard HEAD` before fetching'
    default: true

  filter:
    description: 'Partially clone against a given filter, overrides sparse-checkout if set'
    default: null

  sparse-checkout:
    description: 'Do a sparse checkout on given patterns (each pattern separated by new lines)'
    default: null

  sparse-checkout-cone-mode:
    description: 'Use cone-mode when doing a sparse checkout'
    default: true

  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    default: 1

  fetch-tags:
    description: 'Fetch tags even if fetch-depth > 0'
    default: false

  show-progress:
    description: 'Show progress status output when fetching'
    default: true

  lfs:
    description: 'Download Git-LFS files'
    default: false

  submodules:
    description: >
      Checkout submodules: `true` to checkout submodules, `recursive` to recursively checkout submodules.
      When `ssh-key` input is not provided, convert SSH URLs to HTTPS.
    default: false

  set-safe-directory:
    description: 'Add repository path as safe.directory for Git global config (`git config --global --add safe.directory <path>`)'
    default: true

  github-server-url:
    description: >
      Base URL for the GitHub instance to clone from.
      Uses environment defaults to fetch from the same instance as the workflow unless specified.
      Example URLs: https://github.com or https://my-ghes-server.example.com
    required: false

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
